
package samples.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleStockQuoteService", targetNamespace = "http://services.samples", wsdlLocation = "http://localhost:9000/services/SimpleStockQuoteService?wsdl")
public class SimpleStockQuoteService
    extends Service
{

    private final static URL SIMPLESTOCKQUOTESERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLESTOCKQUOTESERVICE_EXCEPTION;
    private final static QName SIMPLESTOCKQUOTESERVICE_QNAME = new QName("http://services.samples", "SimpleStockQuoteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/services/SimpleStockQuoteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLESTOCKQUOTESERVICE_WSDL_LOCATION = url;
        SIMPLESTOCKQUOTESERVICE_EXCEPTION = e;
    }

    public SimpleStockQuoteService() {
        super(__getWsdlLocation(), SIMPLESTOCKQUOTESERVICE_QNAME);
    }

    public SimpleStockQuoteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLESTOCKQUOTESERVICE_QNAME, features);
    }

    public SimpleStockQuoteService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLESTOCKQUOTESERVICE_QNAME);
    }

    public SimpleStockQuoteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLESTOCKQUOTESERVICE_QNAME, features);
    }

    public SimpleStockQuoteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleStockQuoteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleStockQuoteServicePortType
     */
    @WebEndpoint(name = "SimpleStockQuoteServiceHttpsSoap11Endpoint")
    public SimpleStockQuoteServicePortType getSimpleStockQuoteServiceHttpsSoap11Endpoint() {
        return super.getPort(new QName("http://services.samples", "SimpleStockQuoteServiceHttpsSoap11Endpoint"), SimpleStockQuoteServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleStockQuoteServicePortType
     */
    @WebEndpoint(name = "SimpleStockQuoteServiceHttpsSoap11Endpoint")
    public SimpleStockQuoteServicePortType getSimpleStockQuoteServiceHttpsSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.samples", "SimpleStockQuoteServiceHttpsSoap11Endpoint"), SimpleStockQuoteServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns SimpleStockQuoteServicePortType
     */
    @WebEndpoint(name = "SimpleStockQuoteServiceHttpSoap11Endpoint")
    public SimpleStockQuoteServicePortType getSimpleStockQuoteServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://services.samples", "SimpleStockQuoteServiceHttpSoap11Endpoint"), SimpleStockQuoteServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleStockQuoteServicePortType
     */
    @WebEndpoint(name = "SimpleStockQuoteServiceHttpSoap11Endpoint")
    public SimpleStockQuoteServicePortType getSimpleStockQuoteServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.samples", "SimpleStockQuoteServiceHttpSoap11Endpoint"), SimpleStockQuoteServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLESTOCKQUOTESERVICE_EXCEPTION!= null) {
            throw SIMPLESTOCKQUOTESERVICE_EXCEPTION;
        }
        return SIMPLESTOCKQUOTESERVICE_WSDL_LOCATION;
    }

}
