
package samples.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SimpleStockQuoteServiceException", targetNamespace = "http://services.samples")
public class SimpleStockQuoteServiceException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SimpleStockQuoteServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SimpleStockQuoteServiceException_Exception(String message, SimpleStockQuoteServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SimpleStockQuoteServiceException_Exception(String message, SimpleStockQuoteServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: samples.services.SimpleStockQuoteServiceException
     */
    public SimpleStockQuoteServiceException getFaultInfo() {
        return faultInfo;
    }

}
